In [1]:
cd '/Volumes/OS X EL CAPITAN/Dropbox/Pints/Pints1/pints'

/Volumes/OS X EL CAPITAN/Dropbox/Pints/Pints1/pints


In [2]:
from __future__ import print_function
import pints
import pints.toy as toy
import pints.plot
import numpy as np

In [3]:
# Load a forward model
model = toy.LogisticModel()

# Create some toy data
real_parameters = [0.015, 500]
times = np.linspace(0, 1000, 1000)
org_values = model.simulate(real_parameters, times)

# Add noise
noise = 10
values = org_values + np.random.normal(0, noise, org_values.shape)
real_parameters = np.array(real_parameters + [noise])

# Get properties of the noise sample
noise_sample_mean = np.mean(values - org_values)
noise_sample_std = np.std(values - org_values)

# Create an object with links to the model and time series
problem = pints.SingleOutputProblem(model, times, values)

# Create a log-likelihood function (adds an extra parameter!)
log_likelihood = pints.UnknownNoiseLogLikelihood(problem)

# Create a uniform prior over both the parameters and the new noise variable
log_prior = pints.UniformLogPrior(
    [0.01, 400, noise * 0.1],
    [0.02, 600, noise * 100],
)

# Create a posterior log-likelihood (log(likelihood * prior))
log_posterior = pints.LogPosterior(log_likelihood, log_prior)

# Choose starting points for n mcmc chains
n_chains = 10
xs = []
for i in range(0, n_chains):
    xs.append(real_parameters * (1 + 0.1 * np.random.rand(3)))

# Create mcmc routine
mcmc = pints.MCMCSampling(log_posterior, n_chains, xs, method=pints.EmceeHammerMCMC)

# Add stopping criterion
mcmc.set_max_iterations(1000)

# Disable logging
mcmc.set_log_to_screen(False)

# Run!
print('Running...')
chains = mcmc.run()
print('Done!')

# Check convergence using rhat criterion
print('R-hat:')
print(pints.rhat_all_params(chains))

# Show traces and histograms
pints.plot.trace(chains)

# Discard warm up
chains = chains[:, 5000:, :]

# Apply thinning
chains = chains[:, ::10, :]

# Look at distribution in chain 0
pints.plot.pairwise(chains[0], kde=True)

# Show graphs
plt.show()

Running...
[-4135.8775518569428, -9569.898592107651, -9232.7070335924163, -3839.0276612064581, -13048.948661645101, -6710.5179137546629, -9597.4074464501064, -11544.134814401508, -10770.063691745192, -8068.1520063638382]
[  1.54803404e-02   5.01571439e+02   1.05589367e+01]
[  1.61986613e-02   5.27812000e+02   1.03751660e+01]
[  1.58642791e-02   5.34880943e+02   1.05413159e+01]
[  1.51311983e-02   5.04813727e+02   1.05804635e+01]
[  1.63707883e-02   5.38880449e+02   1.03971167e+01]
[-4156.9537103687417, -9534.0154498705451, -9603.9948547548756, -4469.3384277214454, -12480.981233100867, -inf, -inf, -inf, -inf, -inf]
[  1.62064747e-02   5.10561706e+02   1.07523057e+01]
[  1.53423039e-02   5.47516491e+02   1.08361754e+01]
[  1.59535428e-02   5.40053950e+02   1.00263745e+01]
[  1.56824019e-02   5.47347809e+02   1.09292401e+01]
[  1.59715371e-02   5.28196738e+02   1.09503590e+01]
[-inf, -inf, -inf, -inf, -inf, -49353.050361838272, -inf, -inf, -inf, -inf]
[-4156.95371037 -4156.95371037 -4156.

pints/_mcmc/_emcee_hammer.py:139: RuntimeWarning: invalid value encountered in add
  self._proposed[self._k[i]] = X_j + self._z[i] * (X_k - X_j)
pints/_boundaries.py:53: RuntimeWarning: invalid value encountered in less
  if np.any(parameters < self._lower):
pints/_boundaries.py:55: RuntimeWarning: invalid value encountered in greater_equal
  if np.any(parameters >= self._upper):
pints/_mcmc/_emcee_hammer.py:139: RuntimeWarning: invalid value encountered in subtract
  self._proposed[self._k[i]] = X_j + self._z[i] * (X_k - X_j)


[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf, nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -

[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]


[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-i

[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf, nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf, nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -

[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -in

[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, -inf, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-i

[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, nan, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]


[-inf -inf -inf]
[ 0.  0.  0.]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, nan, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, -inf, nan, nan, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[nan, nan, nan, -inf, nan, -inf, -inf, -inf, -inf, -inf]
[-inf -inf -inf]
[ 0.  0.  0.]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf -inf -inf]
[-inf, -inf, -inf, -inf, -inf, nan, -inf, -inf, -inf, -inf]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[-inf -inf -inf]
[ 0.  0.  0.]
[nan, nan, nan, -inf

/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:112: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
pints/_diagnostics.py:79: RuntimeWarning: invalid value encountered in subtract
  return (t / (m - 1.0)) * np.sum((mu - mu_overall) ** 2)
/anaconda2/lib/python2.7/site-packages/numpy/core/function_base.py:128: RuntimeWarning: invalid value encountered in multiply
  y = y * step
/anaconda2/lib/python2.7/site-packages/numpy/core/function_base.py:135: RuntimeWarning: invalid value encountered in add
  y += start


ValueError: range parameter must be finite.

In [ ]:
chains

In [ ]:
[x for x in xs]

In [ ]:
[x for x + np.random.rand(3) in xs]

In [ ]:
x_start = []
for i in range(0, 10):
    x_start.append(xs[0] + np.random.rand(3))

In [ ]:
for i in range(0, n_chains):
    print(log_posterior(xs[i]))


In [ ]:
xs

In [ ]:
np.zeros(5, dtype='int')

In [ ]:
a = [1,2,3,4]

In [ ]:
b = a

In [ ]:
np.random.permutation(a)

In [ ]:
a

In [ ]:
b

In [ ]:
10 % 10