# Inference: Adaptive Covariance MCMC

This example shows you how to perform Bayesian inference on a time series, using [Adaptive Covariance MCMC](http://pints.readthedocs.io/en/latest/mcmc_samplers/adaptive_covariance_mcmc.html).

It follows on from the [first sampling example](./sampling-first-example.ipynb).

In [1]:
import os
os.chdir('C:/Users/bclamber/Desktop/AllPints/pints4/pints')
from __future__ import print_function
import pints
import pints.toy as toy
import pints.plot
import numpy as np
import matplotlib.pyplot as plt

# Load a forward model
model = toy.LogisticModel()

# Create some toy data
real_parameters = [0.015, 500]
times = np.linspace(0, 1000, 1000)
org_values = model.simulate(real_parameters, times)

# Add noise
noise = 10
values = org_values + np.random.normal(0, noise, org_values.shape)
real_parameters = np.array(real_parameters + [noise])

# Get properties of the noise sample
noise_sample_mean = np.mean(values - org_values)
noise_sample_std = np.std(values - org_values)

# Create an object with links to the model and time series
problem = pints.SingleOutputProblem(model, times, values)

# Create a log-likelihood function (adds an extra parameter!)
log_likelihood = pints.UnknownNoiseLogLikelihood(problem)

# Create a uniform prior over both the parameters and the new noise variable
log_prior = pints.UniformLogPrior(
    [0.01, 400, noise*0.1],
    [0.02, 600, noise*100]
)

# Create a posterior log-likelihood (log(likelihood * prior))
log_posterior = pints.LogPosterior(log_likelihood, log_prior)

# Choose starting points for 3 mcmc chains
xs = [
    real_parameters * 1.1,
    real_parameters * 0.9,
    real_parameters * 1.15,
]

# Create mcmc routine
mcmc = pints.MCMCSampling(log_posterior, 3, xs, method=pints.AdaptiveCovarianceRemiMCMC)

# Add stopping criterion
mcmc.set_max_iterations(4000)

# Start adapting after 1000 iterations
mcmc.set_initial_phase_iterations(1000)

# Disable logging mode
mcmc.set_log_to_screen(False)

# Run!
print('Running...')
chains = mcmc.run()
print('Done!')

# Show traces and histograms
pints.plot.trace(chains)

# Discard warm up
chains = chains[:, 2000:, :]

# Check convergence using rhat criterion
print('R-hat:')
print(pints.rhat_all_params(chains))

# Look at distribution in chain 0
pints.plot.pairwise(chains[0], kde=True)

# Show graphs
plt.show()

Running...
None
None
None
[  1.65000000e-02   5.50000000e+02   1.10000000e+01]
[  1.35000000e-02   4.50000000e+02   9.00000000e+00]
[  1.72500000e-02   5.75000000e+02   1.15000000e+01]
[  1.65000000e-02   5.50000000e+02   1.10000000e+01]
[  1.35000000e-02   4.50000000e+02   9.00000000e+00]
[  1.72500000e-02   5.75000000e+02   1.15000000e+01]
[  1.65000000e-02   5.50000000e+02   1.10000000e+01]
[  1.35000000e-02   4.50000000e+02   9.00000000e+00]
[  1.72500000e-02   5.75000000e+02   1.15000000e+01]
[  1.65000000e-02   5.50000000e+02   1.10000000e+01]
[  1.35000000e-02   4.50000000e+02   9.00000000e+00]
[  1.72500000e-02   5.75000000e+02   1.15000000e+01]
[  1.65000000e-02   5.50000000e+02   1.10000000e+01]
[  1.35000000e-02   4.50000000e+02   9.00000000e+00]
[  1.72500000e-02   5.75000000e+02   1.15000000e+01]
[  1.65000000e-02   5.50000000e+02   1.10000000e+01]
[  1.53171015e-02   4.47589686e+02   9.46939490e+00]
[  1.72500000e-02   5.75000000e+02   1.15000000e+01]
[  1.65000000e-02   

[  1.39112932e-02   5.53404910e+02   1.08160508e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.29380633e-02   5.68837180e+02   1.16196190e+01]
[  1.39112932e-02   5.53404910e+02   1.08160508e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.29380633e-02   5.68837180e+02   1.16196190e+01]
[  1.39112932e-02   5.53404910e+02   1.08160508e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.29380633e-02   5.68837180e+02   1.16196190e+01]
[  1.39112932e-02   5.53404910e+02   1.08160508e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.29380633e-02   5.68837180e+02   1.16196190e+01]
[  1.39112932e-02   5.53404910e+02   1.08160508e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.29380633e-02   5.68837180e+02   1.16196190e+01]
[  1.39112932e-02   5.53404910e+02   1.08160508e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.29380633e-02   5.68837180e+02   1.16196190e+01]
[  1.39112932e-02   5.53404910e+02   1.0816050

[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.38634551e-02   5.57796593e+02   1.14236902e+01]
[  1.47437186e-02   5.49880204e+02   1.05927255e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.38634551e-02   5.57796593e+02   1.14236902e+01]
[  1.47437186e-02   5.49880204e+02   1.05927255e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.38634551e-02   5.57796593e+02   1.14236902e+01]
[  1.47437186e-02   5.49880204e+02   1.05927255e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.38634551e-02   5.57796593e+02   1.14236902e+01]
[  1.47437186e-02   5.49880204e+02   1.05927255e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.38634551e-02   5.57796593e+02   1.14236902e+01]
[  1.47437186e-02   5.49880204e+02   1.05927255e+01]
[  1.58554739e-02   4.53153913e+02   9.44102485e+00]
[  1.38634551e-02   5.57796593e+02   1.14236902e+01]
[  1.47437186e-02   5.49880204e+02   1.05927255e+01]
[  1.58554739e-02   4.53153913e+02   9.4410248

[  1.52926293e-02   4.53578385e+02   9.74425450e+00]
[  1.47198881e-02   5.51473283e+02   1.17259674e+01]
[  1.46156031e-02   5.51585547e+02   1.09255230e+01]
[  1.52926293e-02   4.53578385e+02   9.74425450e+00]
[  1.47198881e-02   5.51473283e+02   1.17259674e+01]
[  1.46156031e-02   5.51585547e+02   1.09255230e+01]
[  1.52926293e-02   4.53578385e+02   9.74425450e+00]
[  1.47198881e-02   5.51473283e+02   1.17259674e+01]
[  1.46156031e-02   5.51585547e+02   1.09255230e+01]
[  1.52926293e-02   4.53578385e+02   9.74425450e+00]
[  1.47198881e-02   5.51473283e+02   1.17259674e+01]
[  1.46156031e-02   5.51585547e+02   1.09255230e+01]
[  1.52926293e-02   4.53578385e+02   9.74425450e+00]
[  1.47198881e-02   5.51473283e+02   1.17259674e+01]
[  1.46156031e-02   5.51585547e+02   1.09255230e+01]
[  1.52926293e-02   4.53578385e+02   9.74425450e+00]
[  1.47198881e-02   5.51473283e+02   1.17259674e+01]
[  1.46156031e-02   5.51585547e+02   1.09255230e+01]
[  1.52926293e-02   4.53578385e+02   9.7442545

[  1.41115965e-02   5.49048416e+02   1.20535198e+01]
[  1.41749343e-02   5.49475544e+02   1.12061200e+01]
[  1.56237998e-02   4.59898898e+02   1.02499521e+01]
[  1.41115965e-02   5.49048416e+02   1.20535198e+01]
[  1.41749343e-02   5.49475544e+02   1.12061200e+01]
[  1.56237998e-02   4.59898898e+02   1.02499521e+01]
[  1.41115965e-02   5.49048416e+02   1.20535198e+01]
[  1.41749343e-02   5.49475544e+02   1.12061200e+01]
[  1.56237998e-02   4.59898898e+02   1.02499521e+01]
[  1.41115965e-02   5.49048416e+02   1.20535198e+01]
[  1.41749343e-02   5.49475544e+02   1.12061200e+01]
[  1.56237998e-02   4.59898898e+02   1.02499521e+01]
[  1.41115965e-02   5.49048416e+02   1.20535198e+01]
[  1.41749343e-02   5.49475544e+02   1.12061200e+01]
[  1.56237998e-02   4.59898898e+02   1.02499521e+01]
[  1.41115965e-02   5.49048416e+02   1.20535198e+01]
[  1.41749343e-02   5.49475544e+02   1.12061200e+01]
[  1.56237998e-02   4.59898898e+02   1.02499521e+01]
[  1.41115965e-02   5.49048416e+02   1.2053519

[  1.39418802e-02   5.47339930e+02   1.23686159e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.54874123e-02   4.63908381e+02   1.16546517e+01]
[  1.39418802e-02   5.47339930e+02   1.23686159e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.54874123e-02   4.63908381e+02   1.16546517e+01]
[  1.39418802e-02   5.47339930e+02   1.23686159e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.54874123e-02   4.63908381e+02   1.16546517e+01]
[  1.39418802e-02   5.47339930e+02   1.23686159e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.54874123e-02   4.63908381e+02   1.16546517e+01]
[  1.39418802e-02   5.47339930e+02   1.23686159e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.54874123e-02   4.63908381e+02   1.16546517e+01]
[  1.39418802e-02   5.47339930e+02   1.23686159e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.54874123e-02   4.63908381e+02   1.16546517e+01]
[  1.39418802e-02   5.47339930e+02   1.2368615

[  1.42015821e-02   5.43925325e+02   1.29917898e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.58366807e-02   4.70550456e+02   1.21490565e+01]
[  1.42015821e-02   5.43925325e+02   1.29917898e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.58366807e-02   4.70550456e+02   1.21490565e+01]
[  1.42015821e-02   5.43925325e+02   1.29917898e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.58366807e-02   4.70550456e+02   1.21490565e+01]
[  1.42015821e-02   5.43925325e+02   1.29917898e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.58366807e-02   4.70550456e+02   1.21490565e+01]
[  1.42015821e-02   5.43925325e+02   1.29917898e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.58366807e-02   4.70550456e+02   1.21490565e+01]
[  1.42015821e-02   5.43925325e+02   1.29917898e+01]
[  1.42574826e-02   5.30843419e+02   1.16584008e+01]
[  1.58366807e-02   4.70550456e+02   1.21490565e+01]
[  1.42015821e-02   5.43925325e+02   1.2991789

[  1.50955435e-02   4.72263032e+02   1.17477380e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.50955435e-02   4.72263032e+02   1.17477380e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.50955435e-02   4.72263032e+02   1.17477380e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.50955435e-02   4.72263032e+02   1.17477380e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.50955435e-02   4.72263032e+02   1.17477380e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.50955435e-02   4.72263032e+02   1.17477380e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.50955435e-02   4.72263032e+02   1.1747738

[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.53320288e-02   4.72139080e+02   1.25095770e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.53320288e-02   4.72139080e+02   1.25095770e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.53320288e-02   4.72139080e+02   1.25095770e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.53320288e-02   4.72139080e+02   1.25095770e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.53320288e-02   4.72139080e+02   1.25095770e+01]
[  1.47787748e-02   5.42492609e+02   1.33647077e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.53320288e-02   4.72139080e+02   1.25095770e+01]
[  1.47787748e-02   5.42492609e+02   1.3364707

[  1.52932848e-02   4.76517867e+02   1.20589540e+01]
[  1.43628739e-02   5.37284704e+02   1.42660670e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.52932848e-02   4.76517867e+02   1.20589540e+01]
[  1.43628739e-02   5.37284704e+02   1.42660670e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.52932848e-02   4.76517867e+02   1.20589540e+01]
[  1.43628739e-02   5.37284704e+02   1.42660670e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.52932848e-02   4.76517867e+02   1.20589540e+01]
[  1.43628739e-02   5.37284704e+02   1.42660670e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.52932848e-02   4.76517867e+02   1.20589540e+01]
[  1.43628739e-02   5.37284704e+02   1.42660670e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.52932848e-02   4.76517867e+02   1.20589540e+01]
[  1.43628739e-02   5.37284704e+02   1.42660670e+01]
[  1.46838228e-02   5.24088657e+02   1.11698588e+01]
[  1.52932848e-02   4.76517867e+02   1.2058954

[  1.47801908e-02   5.02207427e+02   1.67539321e+01]
[  1.49856139e-02   5.00384660e+02   1.12865746e+01]
[  1.48246222e-02   4.91097947e+02   1.36760037e+01]
[  1.47630593e-02   5.04400635e+02   1.65988597e+01]
[  1.49856139e-02   5.00384660e+02   1.12865746e+01]
[  1.48246222e-02   4.91097947e+02   1.36760037e+01]
[  1.48366189e-02   5.02541017e+02   1.67326324e+01]
[  1.49856139e-02   5.00384660e+02   1.12865746e+01]
[  1.47406789e-02   4.93635427e+02   1.39577152e+01]
[  1.48366189e-02   5.02541017e+02   1.67326324e+01]
[  1.49871425e-02   5.00449587e+02   1.12861632e+01]
[  1.46969139e-02   4.96063368e+02   1.42266416e+01]
[  1.48366189e-02   5.02541017e+02   1.67326324e+01]
[  1.49990126e-02   5.00316230e+02   1.12850309e+01]
[  1.46969139e-02   4.96063368e+02   1.42266416e+01]
[  1.48366189e-02   5.02541017e+02   1.67326324e+01]
[  1.49911435e-02   5.00534939e+02   1.12852867e+01]
[  1.46579106e-02   4.98780845e+02   1.45276178e+01]
[  1.49468605e-02   5.01869807e+02   1.6783000

[  1.49984534e-02   5.00964575e+02   1.68407020e+01]
[  1.49963279e-02   4.99518636e+02   1.05305533e+01]
[  1.49899422e-02   4.97703941e+02   1.44092408e+01]
[  1.49310014e-02   5.02213555e+02   1.67657018e+01]
[  1.49963279e-02   4.99518636e+02   1.05305533e+01]
[  1.49868843e-02   4.98136061e+02   1.44555625e+01]
[  1.49310014e-02   5.02213555e+02   1.67657018e+01]
[  1.49963279e-02   4.99518636e+02   1.05305533e+01]
[  1.49745540e-02   4.98423099e+02   1.44880627e+01]
[  1.49819123e-02   5.01249236e+02   1.68182711e+01]
[  1.49963279e-02   4.99518636e+02   1.05305533e+01]
[  1.49745540e-02   4.98423099e+02   1.44880627e+01]
[  1.49819123e-02   5.01249236e+02   1.68182711e+01]
[  1.49963279e-02   4.99518636e+02   1.05305533e+01]
[  1.49745540e-02   4.98423099e+02   1.44880627e+01]
[  1.49819123e-02   5.01249236e+02   1.68182711e+01]
[  1.49963279e-02   4.99518636e+02   1.05305533e+01]
[  1.49745540e-02   4.98423099e+02   1.44880627e+01]
[  1.49819123e-02   5.01249236e+02   1.6818271

[  1.50520976e-02   4.99066254e+02   1.42478456e+01]
[  1.50860954e-02   4.97906363e+02   1.10775394e+01]
[  1.49553817e-02   5.00917202e+02   9.93093562e+00]
[  1.50520976e-02   4.99066254e+02   1.42478456e+01]
[  1.50860954e-02   4.97906363e+02   1.10775394e+01]
[  1.49553817e-02   5.00917202e+02   9.93093562e+00]
[  1.50520976e-02   4.99066254e+02   1.42478456e+01]
[  1.50860954e-02   4.97906363e+02   1.10775394e+01]
[  1.49553817e-02   5.00917202e+02   9.93093562e+00]
[  1.50582501e-02   4.97884443e+02   1.39945882e+01]
[  1.50860954e-02   4.97906363e+02   1.10775394e+01]
[  1.49553817e-02   5.00917202e+02   9.93093562e+00]
[  1.50582501e-02   4.97884443e+02   1.39945882e+01]
[  1.50860954e-02   4.97906363e+02   1.10775394e+01]
[  1.49553817e-02   5.00917202e+02   9.93093562e+00]
[  1.50582501e-02   4.97884443e+02   1.39945882e+01]
[  1.50860954e-02   4.97906363e+02   1.10775394e+01]
[  1.49553817e-02   5.00917202e+02   9.93093562e+00]
[  1.50582501e-02   4.97884443e+02   1.3994588

[  1.49676761e-02   5.00766481e+02   9.92973361e+00]
[  1.50379379e-02   4.96609088e+02   1.15386501e+01]
[  1.50076356e-02   4.99070352e+02   1.12275373e+01]
[  1.49676761e-02   5.00766481e+02   9.92973361e+00]
[  1.50379379e-02   4.96609088e+02   1.15386501e+01]
[  1.50076356e-02   4.99070352e+02   1.12275373e+01]
[  1.49715037e-02   5.01049925e+02   1.04849042e+01]
[  1.50379379e-02   4.96609088e+02   1.15386501e+01]
[  1.50076356e-02   4.99070352e+02   1.12275373e+01]
[  1.49715037e-02   5.01049925e+02   1.04849042e+01]
[  1.50379379e-02   4.96609088e+02   1.15386501e+01]
[  1.50076356e-02   4.99070352e+02   1.12275373e+01]
[  1.49715037e-02   5.01049925e+02   1.04849042e+01]
[  1.50379379e-02   4.96609088e+02   1.15386501e+01]
[  1.50076356e-02   4.99070352e+02   1.12275373e+01]
[  1.49828836e-02   5.01008852e+02   1.03696716e+01]
[  1.50379379e-02   4.96609088e+02   1.15386501e+01]
[  1.50076356e-02   4.99070352e+02   1.12275373e+01]
[  1.49828836e-02   5.01008852e+02   1.0369671

[  1.49649547e-02   4.99745978e+02   9.98349712e+00]
[  1.49670626e-02   5.00577229e+02   1.09235019e+01]
[  1.49788637e-02   5.00278461e+02   1.03686156e+01]
[  1.49649547e-02   4.99745978e+02   9.98349712e+00]
[  1.49670626e-02   5.00577229e+02   1.09235019e+01]
[  1.49788637e-02   5.00278461e+02   1.03686156e+01]
[  1.49649547e-02   4.99745978e+02   9.98349712e+00]
[  1.49670626e-02   5.00577229e+02   1.09235019e+01]
[  1.49788637e-02   5.00278461e+02   1.03686156e+01]
[  1.49649547e-02   4.99745978e+02   9.98349712e+00]
[  1.49617247e-02   5.00763768e+02   1.00647992e+01]
[  1.49788637e-02   5.00278461e+02   1.03686156e+01]
[  1.49649547e-02   4.99745978e+02   9.98349712e+00]
[  1.49629684e-02   5.00501220e+02   1.03102938e+01]
[  1.49788637e-02   5.00278461e+02   1.03686156e+01]
[  1.49649547e-02   4.99745978e+02   9.98349712e+00]
[  1.49629684e-02   5.00501220e+02   1.03102938e+01]
[  1.49788637e-02   5.00278461e+02   1.03686156e+01]
[  1.49792835e-02   5.00032071e+02   1.0627370

[  1.49896606e-02   4.99938171e+02   1.07996603e+01]
[  1.49693137e-02   5.00074030e+02   1.02933853e+01]
[  1.49631566e-02   5.00658359e+02   1.05719621e+01]
[  1.49896606e-02   4.99938171e+02   1.07996603e+01]
[  1.49693137e-02   5.00074030e+02   1.02933853e+01]
[  1.49772807e-02   4.99745618e+02   1.08472507e+01]
[  1.49896606e-02   4.99938171e+02   1.07996603e+01]
[  1.49693137e-02   5.00074030e+02   1.02933853e+01]
[  1.49772807e-02   4.99745618e+02   1.08472507e+01]
[  1.49896606e-02   4.99938171e+02   1.07996603e+01]
[  1.49693137e-02   5.00074030e+02   1.02933853e+01]
[  1.49717930e-02   5.00074935e+02   1.08963394e+01]
[  1.49896606e-02   4.99938171e+02   1.07996603e+01]
[  1.49693137e-02   5.00074030e+02   1.02933853e+01]
[  1.49717930e-02   5.00074935e+02   1.08963394e+01]
[  1.49896606e-02   4.99938171e+02   1.07996603e+01]
[  1.49693137e-02   5.00074030e+02   1.02933853e+01]
[  1.49717930e-02   5.00074935e+02   1.08963394e+01]
[  1.49896606e-02   4.99938171e+02   1.0799660

[  1.49572841e-02   5.00787436e+02   1.03183623e+01]
[  1.49925460e-02   4.99708743e+02   9.77234497e+00]
[  1.49678629e-02   5.00382446e+02   1.02817455e+01]
[  1.49572841e-02   5.00787436e+02   1.03183623e+01]
[  1.50058975e-02   5.00105583e+02   1.01218116e+01]
[  1.49678629e-02   5.00382446e+02   1.02817455e+01]
[  1.49572841e-02   5.00787436e+02   1.03183623e+01]
[  1.49919048e-02   5.00008723e+02   1.03548793e+01]
[  1.49678629e-02   5.00382446e+02   1.02817455e+01]
[  1.49823097e-02   5.00153338e+02   1.04220546e+01]
[  1.49919048e-02   5.00008723e+02   1.03548793e+01]
[  1.49678629e-02   5.00382446e+02   1.02817455e+01]
[  1.49823097e-02   5.00153338e+02   1.04220546e+01]
[  1.49919048e-02   5.00008723e+02   1.03548793e+01]
[  1.49678629e-02   5.00382446e+02   1.02817455e+01]
[  1.49823097e-02   5.00153338e+02   1.04220546e+01]
[  1.49763569e-02   4.99779506e+02   1.06371366e+01]
[  1.49678629e-02   5.00382446e+02   1.02817455e+01]
[  1.49823097e-02   5.00153338e+02   1.0422054

[  1.49807155e-02   5.00866199e+02   1.03828467e+01]
[  1.49619822e-02   5.01058589e+02   1.05058964e+01]
[  1.49510086e-02   4.99775860e+02   1.00235334e+01]
[  1.49821668e-02   5.01023482e+02   1.04986188e+01]
[  1.49619822e-02   5.01058589e+02   1.05058964e+01]
[  1.49510086e-02   4.99775860e+02   1.00235334e+01]
[  1.50032827e-02   5.00069452e+02   1.05785165e+01]
[  1.49619822e-02   5.01058589e+02   1.05058964e+01]
[  1.49510086e-02   4.99775860e+02   1.00235334e+01]
[  1.49996855e-02   5.00038107e+02   1.08359273e+01]
[  1.49619822e-02   5.01058589e+02   1.05058964e+01]
[  1.49510086e-02   4.99775860e+02   1.00235334e+01]
[  1.49691691e-02   4.99683931e+02   1.05765277e+01]
[  1.49619822e-02   5.01058589e+02   1.05058964e+01]
[  1.49510086e-02   4.99775860e+02   1.00235334e+01]
[  1.49691691e-02   4.99683931e+02   1.05765277e+01]
[  1.49619822e-02   5.01058589e+02   1.05058964e+01]
[  1.49510086e-02   4.99775860e+02   1.00235334e+01]
[  1.49691691e-02   4.99683931e+02   1.0576527

[  1.49661723e-02   5.00533982e+02   9.74282284e+00]
[  1.49764892e-02   5.00220431e+02   1.11026615e+01]
[  1.49808033e-02   5.00016551e+02   1.04246668e+01]
[  1.49661723e-02   5.00533982e+02   9.74282284e+00]
[  1.49498499e-02   5.00719720e+02   1.08348705e+01]
[  1.49808033e-02   5.00016551e+02   1.04246668e+01]
[  1.49235768e-02   5.00515133e+02   1.02125889e+01]
[  1.49498499e-02   5.00719720e+02   1.08348705e+01]
[  1.49808033e-02   5.00016551e+02   1.04246668e+01]
[  1.49398383e-02   5.00074097e+02   1.01543079e+01]
[  1.49498499e-02   5.00719720e+02   1.08348705e+01]
[  1.49751057e-02   4.99303815e+02   1.02099213e+01]
[  1.49398383e-02   5.00074097e+02   1.01543079e+01]
[  1.49242446e-02   5.01258147e+02   1.08469600e+01]
[  1.49573133e-02   4.99644633e+02   1.00829440e+01]
[  1.49443869e-02   5.00145729e+02   1.01448834e+01]
[  1.49242446e-02   5.01258147e+02   1.08469600e+01]
[  1.49573133e-02   4.99644633e+02   1.00829440e+01]
[  1.49443869e-02   5.00145729e+02   1.0144883

[  1.49628159e-02   4.99798056e+02   1.04848730e+01]
[  1.49926741e-02   4.99934789e+02   1.06102164e+01]
[  1.49785704e-02   5.00006493e+02   1.01331357e+01]
[  1.49785678e-02   4.99792908e+02   1.04479043e+01]
[  1.49926741e-02   4.99934789e+02   1.06102164e+01]
[  1.49785704e-02   5.00006493e+02   1.01331357e+01]
[  1.49785678e-02   4.99792908e+02   1.04479043e+01]
[  1.49926741e-02   4.99934789e+02   1.06102164e+01]
[  1.49575623e-02   4.99853678e+02   1.03777992e+01]
[  1.49785678e-02   4.99792908e+02   1.04479043e+01]
[  1.49926741e-02   4.99934789e+02   1.06102164e+01]
[  1.49575623e-02   4.99853678e+02   1.03777992e+01]
[  1.49808250e-02   4.99326275e+02   1.03167484e+01]
[  1.49926741e-02   4.99934789e+02   1.06102164e+01]
[  1.49575623e-02   4.99853678e+02   1.03777992e+01]
[  1.49907844e-02   5.00353804e+02   1.05394834e+01]
[  1.49801858e-02   5.00554911e+02   1.07199098e+01]
[  1.49575623e-02   4.99853678e+02   1.03777992e+01]
[  1.49907844e-02   5.00353804e+02   1.0539483

[  1.49580047e-02   5.00829098e+02   1.04519668e+01]
[  1.49700088e-02   4.99999359e+02   1.01764180e+01]
[  1.49553497e-02   5.00088019e+02   1.02415892e+01]
[  1.49580047e-02   5.00829098e+02   1.04519668e+01]
[  1.49700088e-02   4.99999359e+02   1.01764180e+01]
[  1.49553497e-02   5.00088019e+02   1.02415892e+01]
[  1.49782804e-02   5.00387780e+02   1.02734953e+01]
[  1.49700088e-02   4.99999359e+02   1.01764180e+01]
[  1.49553497e-02   5.00088019e+02   1.02415892e+01]
[  1.49782804e-02   5.00387780e+02   1.02734953e+01]
[  1.49700088e-02   4.99999359e+02   1.01764180e+01]
[  1.49553497e-02   5.00088019e+02   1.02415892e+01]
[  1.49782804e-02   5.00387780e+02   1.02734953e+01]
[  1.49700088e-02   4.99999359e+02   1.01764180e+01]
[  1.49553497e-02   5.00088019e+02   1.02415892e+01]
[  1.49782804e-02   5.00387780e+02   1.02734953e+01]
[  1.49700088e-02   4.99999359e+02   1.01764180e+01]
[  1.49694543e-02   4.99961932e+02   1.04036850e+01]
[  1.49782804e-02   5.00387780e+02   1.0273495

[  1.49599452e-02   5.00962681e+02   1.02084172e+01]
[  1.49840076e-02   5.00305642e+02   1.07331732e+01]
[  1.49676491e-02   4.99658859e+02   1.02405715e+01]
[  1.49599452e-02   5.00962681e+02   1.02084172e+01]
[  1.49840076e-02   5.00305642e+02   1.07331732e+01]
[  1.49676491e-02   4.99658859e+02   1.02405715e+01]
[  1.49599452e-02   5.00962681e+02   1.02084172e+01]
[  1.49840076e-02   5.00305642e+02   1.07331732e+01]
[  1.49676491e-02   4.99658859e+02   1.02405715e+01]
[  1.49599452e-02   5.00962681e+02   1.02084172e+01]
[  1.49840076e-02   5.00305642e+02   1.07331732e+01]
[  1.49519335e-02   5.00253506e+02   1.03796495e+01]
[  1.49599452e-02   5.00962681e+02   1.02084172e+01]
[  1.49840076e-02   5.00305642e+02   1.07331732e+01]
[  1.49519335e-02   5.00253506e+02   1.03796495e+01]
[  1.49599452e-02   5.00962681e+02   1.02084172e+01]
[  1.49840076e-02   5.00305642e+02   1.07331732e+01]
[  1.49597405e-02   5.00244145e+02   1.04813774e+01]
[  1.49599452e-02   5.00962681e+02   1.0208417

[  1.49778148e-02   4.99840887e+02   1.01334783e+01]
[  1.49689222e-02   4.99763122e+02   1.06604271e+01]
[  1.49653904e-02   5.00918009e+02   1.03751587e+01]
[  1.49778148e-02   4.99840887e+02   1.01334783e+01]
[  1.49689222e-02   4.99763122e+02   1.06604271e+01]
[  1.49653904e-02   5.00918009e+02   1.03751587e+01]
[  1.49778148e-02   4.99840887e+02   1.01334783e+01]
[  1.49689222e-02   4.99763122e+02   1.06604271e+01]
[  1.49653904e-02   5.00918009e+02   1.03751587e+01]
[  1.49778148e-02   4.99840887e+02   1.01334783e+01]
[  1.49689222e-02   4.99763122e+02   1.06604271e+01]
[  1.49653904e-02   5.00918009e+02   1.03751587e+01]
[  1.49778148e-02   4.99840887e+02   1.01334783e+01]
[  1.49689222e-02   4.99763122e+02   1.06604271e+01]
[  1.49417564e-02   5.00673170e+02   1.05349842e+01]
[  1.49610947e-02   5.00141731e+02   1.01120923e+01]
[  1.49781791e-02   4.99479593e+02   1.04118596e+01]
[  1.49417564e-02   5.00673170e+02   1.05349842e+01]
[  1.49610947e-02   5.00141731e+02   1.0112092

[  1.49898483e-02   5.00213257e+02   1.07852996e+01]
[  1.49737695e-02   5.00768170e+02   1.02421762e+01]
[  1.49527331e-02   5.00315917e+02   1.05970338e+01]
[  1.49898483e-02   5.00213257e+02   1.07852996e+01]
[  1.49737695e-02   5.00768170e+02   1.02421762e+01]
[  1.49527331e-02   5.00315917e+02   1.05970338e+01]
[  1.49898483e-02   5.00213257e+02   1.07852996e+01]
[  1.49737695e-02   5.00768170e+02   1.02421762e+01]
[  1.49527331e-02   5.00315917e+02   1.05970338e+01]
[  1.49898483e-02   5.00213257e+02   1.07852996e+01]
[  1.49737695e-02   5.00768170e+02   1.02421762e+01]
[  1.49527331e-02   5.00315917e+02   1.05970338e+01]
[  1.49834576e-02   5.00114236e+02   1.06993561e+01]
[  1.49670929e-02   5.00320881e+02   1.02944781e+01]
[  1.49527331e-02   5.00315917e+02   1.05970338e+01]
[  1.49834576e-02   5.00114236e+02   1.06993561e+01]
[  1.49637798e-02   4.99947434e+02   1.02492618e+01]
[  1.49527331e-02   5.00315917e+02   1.05970338e+01]
[  1.49834576e-02   5.00114236e+02   1.0699356

[  1.49573778e-02   4.99088421e+02   1.02992275e+01]
[  1.49753283e-02   4.99734449e+02   1.04309347e+01]
[  1.49835736e-02   4.99361917e+02   1.02139216e+01]
[  1.49581628e-02   5.00100483e+02   1.10545233e+01]
[  1.49753283e-02   4.99734449e+02   1.04309347e+01]
[  1.49311976e-02   5.00311330e+02   1.04576473e+01]
[  1.49581628e-02   5.00100483e+02   1.10545233e+01]
[  1.49753283e-02   4.99734449e+02   1.04309347e+01]
[  1.49311976e-02   5.00311330e+02   1.04576473e+01]
[  1.49210548e-02   5.01163708e+02   1.08121773e+01]
[  1.49753283e-02   4.99734449e+02   1.04309347e+01]
[  1.49311976e-02   5.00311330e+02   1.04576473e+01]
[  1.49521068e-02   5.00873589e+02   1.08500556e+01]
[  1.49753283e-02   4.99734449e+02   1.04309347e+01]
[  1.49863081e-02   5.00097493e+02   1.01640419e+01]
[  1.49671564e-02   5.00500873e+02   1.04215986e+01]
[  1.49753283e-02   4.99734449e+02   1.04309347e+01]
[  1.49863081e-02   5.00097493e+02   1.01640419e+01]
[  1.49671564e-02   5.00500873e+02   1.0421598

[  1.49618423e-02   5.00354279e+02   1.04007290e+01]
[  1.49578888e-02   5.00035668e+02   1.01634708e+01]
[  1.49836510e-02   5.00426118e+02   1.00819981e+01]
[  1.49618423e-02   5.00354279e+02   1.04007290e+01]
[  1.49578888e-02   5.00035668e+02   1.01634708e+01]
[  1.49836510e-02   5.00426118e+02   1.00819981e+01]
[  1.49618423e-02   5.00354279e+02   1.04007290e+01]
[  1.49578888e-02   5.00035668e+02   1.01634708e+01]
[  1.49836510e-02   5.00426118e+02   1.00819981e+01]
[  1.49618423e-02   5.00354279e+02   1.04007290e+01]
[  1.49578888e-02   5.00035668e+02   1.01634708e+01]
[  1.49734023e-02   5.01034553e+02   1.06193198e+01]
[  1.49766635e-02   5.00465643e+02   1.05311090e+01]
[  1.49578888e-02   5.00035668e+02   1.01634708e+01]
[  1.49755367e-02   5.00489193e+02   1.03988904e+01]
[  1.49766635e-02   5.00465643e+02   1.05311090e+01]
[  1.49578888e-02   5.00035668e+02   1.01634708e+01]
[  1.49755367e-02   5.00489193e+02   1.03988904e+01]
[  1.49766635e-02   5.00465643e+02   1.0531109

[  1.49626433e-02   5.01190928e+02   1.01006942e+01]
[  1.49634456e-02   5.00413983e+02   9.93572332e+00]
[  1.49931649e-02   4.99899733e+02   1.05103829e+01]
[  1.49690921e-02   5.00479596e+02   1.10078201e+01]
[  1.49634456e-02   5.00413983e+02   9.93572332e+00]
[  1.49931649e-02   4.99899733e+02   1.05103829e+01]
[  1.49690921e-02   5.00479596e+02   1.10078201e+01]
[  1.49634456e-02   5.00413983e+02   9.93572332e+00]
[  1.49854506e-02   5.00176038e+02   1.04912456e+01]
[  1.49629356e-02   5.00366740e+02   1.05660799e+01]
[  1.49634456e-02   5.00413983e+02   9.93572332e+00]
[  1.49854506e-02   5.00176038e+02   1.04912456e+01]
[  1.49629356e-02   5.00366740e+02   1.05660799e+01]
[  1.49634456e-02   5.00413983e+02   9.93572332e+00]
[  1.49854506e-02   5.00176038e+02   1.04912456e+01]
[  1.49629356e-02   5.00366740e+02   1.05660799e+01]
[  1.49634456e-02   5.00413983e+02   9.93572332e+00]
[  1.49491721e-02   5.00304271e+02   1.03558592e+01]
[  1.49676863e-02   5.00685320e+02   1.0214996

[  1.49957384e-02   4.99741299e+02   1.00856419e+01]
[  1.49598808e-02   5.00071861e+02   1.01978691e+01]
[  1.49507295e-02   5.00550410e+02   1.02679972e+01]
[  1.49957384e-02   4.99741299e+02   1.00856419e+01]
[  1.49598808e-02   5.00071861e+02   1.01978691e+01]
[  1.49507295e-02   5.00550410e+02   1.02679972e+01]
[  1.49957384e-02   4.99741299e+02   1.00856419e+01]
[  1.49598808e-02   5.00071861e+02   1.01978691e+01]
[  1.49642049e-02   5.00568987e+02   1.06011245e+01]
[  1.49957384e-02   4.99741299e+02   1.00856419e+01]
[  1.49598808e-02   5.00071861e+02   1.01978691e+01]
[  1.49642049e-02   5.00568987e+02   1.06011245e+01]
[  1.49957384e-02   4.99741299e+02   1.00856419e+01]
[  1.49598808e-02   5.00071861e+02   1.01978691e+01]
[  1.49642049e-02   5.00568987e+02   1.06011245e+01]
[  1.49957384e-02   4.99741299e+02   1.00856419e+01]
[  1.49598808e-02   5.00071861e+02   1.01978691e+01]
[  1.49642049e-02   5.00568987e+02   1.06011245e+01]
[  1.49957384e-02   4.99741299e+02   1.0085641

[  1.49695973e-02   5.00589930e+02   1.04050847e+01]
[  1.49452704e-02   5.00691788e+02   1.03963569e+01]
[  1.49652243e-02   5.01289288e+02   1.06254962e+01]
[  1.49843877e-02   5.00407987e+02   9.99528304e+00]
[  1.49452704e-02   5.00691788e+02   1.03963569e+01]
[  1.49652243e-02   5.01289288e+02   1.06254962e+01]
[  1.49843877e-02   5.00407987e+02   9.99528304e+00]
[  1.49452704e-02   5.00691788e+02   1.03963569e+01]
[  1.49959533e-02   5.00290568e+02   1.06962856e+01]
[  1.49843877e-02   5.00407987e+02   9.99528304e+00]
[  1.49452704e-02   5.00691788e+02   1.03963569e+01]
[  1.49959533e-02   5.00290568e+02   1.06962856e+01]
[  1.49689250e-02   5.00001127e+02   9.96023981e+00]
[  1.49452704e-02   5.00691788e+02   1.03963569e+01]
[  1.49555945e-02   5.00680257e+02   1.09524746e+01]
[  1.49689250e-02   5.00001127e+02   9.96023981e+00]
[  1.49610665e-02   4.99539600e+02   1.01589352e+01]
[  1.49555945e-02   5.00680257e+02   1.09524746e+01]
[  1.49689250e-02   5.00001127e+02   9.9602398

[  1.49736949e-02   5.00008631e+02   1.02419672e+01]
[  1.49628264e-02   4.99595919e+02   9.84157217e+00]
[  1.49814862e-02   4.99549766e+02   1.05799338e+01]
[  1.49736949e-02   5.00008631e+02   1.02419672e+01]
[  1.49628264e-02   4.99595919e+02   9.84157217e+00]
[  1.49814862e-02   4.99549766e+02   1.05799338e+01]
[  1.49736949e-02   5.00008631e+02   1.02419672e+01]
[  1.49628264e-02   4.99595919e+02   9.84157217e+00]
[  1.49684769e-02   4.99342476e+02   1.06893915e+01]
[  1.49736949e-02   5.00008631e+02   1.02419672e+01]
[  1.49628264e-02   4.99595919e+02   9.84157217e+00]
[  1.49684769e-02   4.99342476e+02   1.06893915e+01]
[  1.49736949e-02   5.00008631e+02   1.02419672e+01]
[  1.49721342e-02   4.99319827e+02   9.84229539e+00]
[  1.49447241e-02   5.00467885e+02   1.07245302e+01]
[  1.49736949e-02   5.00008631e+02   1.02419672e+01]
[  1.49721342e-02   4.99319827e+02   9.84229539e+00]
[  1.49447241e-02   5.00467885e+02   1.07245302e+01]
[  1.49736949e-02   5.00008631e+02   1.0241967

[  1.49780835e-02   5.01192094e+02   1.02826439e+01]
[  1.49565623e-02   4.99431199e+02   1.05626646e+01]
[  1.49530170e-02   5.01144507e+02   1.05326477e+01]
[  1.49780835e-02   5.01192094e+02   1.02826439e+01]
[  1.49565623e-02   4.99431199e+02   1.05626646e+01]
[  1.49530170e-02   5.01144507e+02   1.05326477e+01]
[  1.49780835e-02   5.01192094e+02   1.02826439e+01]
[  1.49565623e-02   4.99431199e+02   1.05626646e+01]
[  1.49530170e-02   5.01144507e+02   1.05326477e+01]
[  1.49780835e-02   5.01192094e+02   1.02826439e+01]
[  1.49565623e-02   4.99431199e+02   1.05626646e+01]
[  1.49519412e-02   5.01585231e+02   1.04011508e+01]
[  1.49780835e-02   5.01192094e+02   1.02826439e+01]
[  1.49565623e-02   4.99431199e+02   1.05626646e+01]
[  1.49519412e-02   5.01585231e+02   1.04011508e+01]
[  1.49780835e-02   5.01192094e+02   1.02826439e+01]
[  1.49503720e-02   4.99236297e+02   1.03833869e+01]
[  1.49519412e-02   5.01585231e+02   1.04011508e+01]
[  1.49682009e-02   5.00102173e+02   1.0519755

[  1.49679768e-02   5.00892049e+02   1.08192080e+01]
[  1.49802901e-02   5.00732491e+02   1.02100008e+01]
[  1.49691956e-02   5.00641594e+02   1.08282496e+01]
[  1.49679768e-02   5.00892049e+02   1.08192080e+01]
[  1.49802901e-02   5.00732491e+02   1.02100008e+01]
[  1.49691956e-02   5.00641594e+02   1.08282496e+01]
[  1.49679768e-02   5.00892049e+02   1.08192080e+01]
[  1.49724935e-02   5.00880866e+02   1.06007962e+01]
[  1.49691956e-02   5.00641594e+02   1.08282496e+01]
[  1.49679768e-02   5.00892049e+02   1.08192080e+01]
[  1.49724935e-02   5.00880866e+02   1.06007962e+01]
[  1.49691956e-02   5.00641594e+02   1.08282496e+01]
[  1.49679768e-02   5.00892049e+02   1.08192080e+01]
[  1.49782956e-02   5.00892830e+02   1.03215996e+01]
[  1.49691956e-02   5.00641594e+02   1.08282496e+01]
[  1.49679768e-02   5.00892049e+02   1.08192080e+01]
[  1.49782956e-02   5.00892830e+02   1.03215996e+01]
[  1.49691956e-02   5.00641594e+02   1.08282496e+01]
[  1.49679768e-02   5.00892049e+02   1.0819208

[  1.49804158e-02   4.99684999e+02   1.09640700e+01]
[  1.49710627e-02   5.00452344e+02   1.01541712e+01]
[  1.49713069e-02   4.99500987e+02   1.05819724e+01]
[  1.49918414e-02   5.00309183e+02   1.06697329e+01]
[  1.49710627e-02   5.00452344e+02   1.01541712e+01]
[  1.49713069e-02   4.99500987e+02   1.05819724e+01]
[  1.49918414e-02   5.00309183e+02   1.06697329e+01]
[  1.49710627e-02   5.00452344e+02   1.01541712e+01]
[  1.49713069e-02   4.99500987e+02   1.05819724e+01]
[  1.49918414e-02   5.00309183e+02   1.06697329e+01]
[  1.49710627e-02   5.00452344e+02   1.01541712e+01]
[  1.49700354e-02   5.00191039e+02   1.07075009e+01]
[  1.49651919e-02   5.00088263e+02   1.09670071e+01]
[  1.49710627e-02   5.00452344e+02   1.01541712e+01]
[  1.49700354e-02   5.00191039e+02   1.07075009e+01]
[  1.49951706e-02   4.99333694e+02   1.08202126e+01]
[  1.49710627e-02   5.00452344e+02   1.01541712e+01]
[  1.49700354e-02   5.00191039e+02   1.07075009e+01]
[  1.49951706e-02   4.99333694e+02   1.0820212

[  1.49680745e-02   5.00783020e+02   1.03329615e+01]
[  1.49665593e-02   5.00245847e+02   1.04244288e+01]
[  1.49691333e-02   5.00476646e+02   1.04843324e+01]
[  1.49680745e-02   5.00783020e+02   1.03329615e+01]
[  1.49665593e-02   5.00245847e+02   1.04244288e+01]
[  1.50209637e-02   5.00510200e+02   1.02577843e+01]
[  1.50013173e-02   5.00054140e+02   1.01033462e+01]
[  1.49665593e-02   5.00245847e+02   1.04244288e+01]
[  1.50209637e-02   5.00510200e+02   1.02577843e+01]
[  1.50013173e-02   5.00054140e+02   1.01033462e+01]
[  1.49665593e-02   5.00245847e+02   1.04244288e+01]
[  1.50209637e-02   5.00510200e+02   1.02577843e+01]
[  1.50013173e-02   5.00054140e+02   1.01033462e+01]
[  1.49665593e-02   5.00245847e+02   1.04244288e+01]
[  1.49994464e-02   5.00801446e+02   9.90685575e+00]
[  1.50013173e-02   5.00054140e+02   1.01033462e+01]
[  1.49665593e-02   5.00245847e+02   1.04244288e+01]
[  1.49994464e-02   5.00801446e+02   9.90685575e+00]
[  1.50013173e-02   5.00054140e+02   1.0103346

[  1.49265603e-02   5.01421386e+02   1.01935162e+01]
[  1.49588610e-02   5.00425273e+02   1.02700610e+01]
[  1.50157344e-02   4.99890541e+02   1.02811733e+01]
[  1.49265603e-02   5.01421386e+02   1.01935162e+01]
[  1.49588610e-02   5.00425273e+02   1.02700610e+01]
[  1.50157344e-02   4.99890541e+02   1.02811733e+01]
[  1.49265603e-02   5.01421386e+02   1.01935162e+01]
[  1.49588610e-02   5.00425273e+02   1.02700610e+01]
[  1.50157344e-02   4.99890541e+02   1.02811733e+01]
[  1.49265603e-02   5.01421386e+02   1.01935162e+01]
[  1.49588610e-02   5.00425273e+02   1.02700610e+01]
[  1.49960855e-02   5.00727020e+02   1.05150826e+01]
[  1.49686223e-02   4.99637628e+02   1.02912682e+01]
[  1.49588610e-02   5.00425273e+02   1.02700610e+01]
[  1.49960855e-02   5.00727020e+02   1.05150826e+01]
[  1.49686223e-02   4.99637628e+02   1.02912682e+01]
[  1.49588610e-02   5.00425273e+02   1.02700610e+01]
[  1.49960855e-02   5.00727020e+02   1.05150826e+01]
[  1.49510291e-02   5.00155268e+02   1.0304129

[  1.49582355e-02   5.00753319e+02   1.04545612e+01]
[  1.49806799e-02   5.00008724e+02   1.04307475e+01]
[  1.49606238e-02   5.00293807e+02   1.05471726e+01]
[  1.49640963e-02   5.00295702e+02   1.07488572e+01]
[  1.49806799e-02   5.00008724e+02   1.04307475e+01]
[  1.49606238e-02   5.00293807e+02   1.05471726e+01]
[  1.49640963e-02   5.00295702e+02   1.07488572e+01]
[  1.49806799e-02   5.00008724e+02   1.04307475e+01]
[  1.49606238e-02   5.00293807e+02   1.05471726e+01]
[  1.49640963e-02   5.00295702e+02   1.07488572e+01]
[  1.49806799e-02   5.00008724e+02   1.04307475e+01]
[  1.49606238e-02   5.00293807e+02   1.05471726e+01]
[  1.49640963e-02   5.00295702e+02   1.07488572e+01]
[  1.49670833e-02   5.00675428e+02   1.03046646e+01]
[  1.49606238e-02   5.00293807e+02   1.05471726e+01]
[  1.49640963e-02   5.00295702e+02   1.07488572e+01]
[  1.49790968e-02   4.99689808e+02   1.01827727e+01]
[  1.49606238e-02   5.00293807e+02   1.05471726e+01]
[  1.49640963e-02   5.00295702e+02   1.0748857

[  1.49629147e-02   4.99762855e+02   1.03604486e+01]
[  1.49427598e-02   5.01262938e+02   1.05818475e+01]
[  1.49773544e-02   5.00548512e+02   1.04545995e+01]
[  1.49629147e-02   4.99762855e+02   1.03604486e+01]
[  1.49743488e-02   5.00661588e+02   9.96929917e+00]
[  1.49682848e-02   5.00823711e+02   1.02828413e+01]
[  1.49610310e-02   5.00159503e+02   1.01860201e+01]
[  1.49559552e-02   5.01346025e+02   1.06059829e+01]
[  1.49603292e-02   5.00732400e+02   1.02984857e+01]
[  1.49610310e-02   5.00159503e+02   1.01860201e+01]
[  1.49559552e-02   5.01346025e+02   1.06059829e+01]
[  1.49603292e-02   5.00732400e+02   1.02984857e+01]
[  1.49610310e-02   5.00159503e+02   1.01860201e+01]
[  1.49697267e-02   5.00739085e+02   1.05553518e+01]
[  1.49603292e-02   5.00732400e+02   1.02984857e+01]
[  1.49610310e-02   5.00159503e+02   1.01860201e+01]
[  1.49697267e-02   5.00739085e+02   1.05553518e+01]
[  1.49603292e-02   5.00732400e+02   1.02984857e+01]
[  1.49610310e-02   5.00159503e+02   1.0186020

[  1.49839681e-02   4.98754909e+02   1.03272876e+01]
[  1.49552619e-02   5.00329904e+02   9.92587264e+00]
[  1.49817919e-02   5.00186112e+02   1.00743003e+01]
[  1.49332856e-02   4.99656602e+02   9.96594982e+00]
[  1.49552619e-02   5.00329904e+02   9.92587264e+00]
[  1.49817919e-02   5.00186112e+02   1.00743003e+01]
[  1.49332856e-02   4.99656602e+02   9.96594982e+00]
[  1.49552619e-02   5.00329904e+02   9.92587264e+00]
[  1.49817919e-02   5.00186112e+02   1.00743003e+01]
[  1.49452259e-02   5.00671860e+02   9.82460118e+00]
[  1.49838037e-02   5.00699091e+02   1.09276310e+01]
[  1.49817919e-02   5.00186112e+02   1.00743003e+01]
[  1.49412922e-02   5.01241244e+02   1.00359332e+01]
[  1.49838037e-02   5.00699091e+02   1.09276310e+01]
[  1.49733355e-02   5.00646707e+02   1.01453224e+01]
[  1.49412922e-02   5.01241244e+02   1.00359332e+01]
[  1.49838037e-02   5.00699091e+02   1.09276310e+01]
[  1.49733355e-02   5.00646707e+02   1.01453224e+01]
[  1.49412922e-02   5.01241244e+02   1.0035933

[  1.49693224e-02   5.00009393e+02   1.01017707e+01]
[  1.49498526e-02   5.00240488e+02   1.02054200e+01]
[  1.49943237e-02   4.99939167e+02   1.06003737e+01]
[  1.49693224e-02   5.00009393e+02   1.01017707e+01]
[  1.49498526e-02   5.00240488e+02   1.02054200e+01]
[  1.49943237e-02   4.99939167e+02   1.06003737e+01]
[  1.49693224e-02   5.00009393e+02   1.01017707e+01]
[  1.49419484e-02   5.00523395e+02   1.02729476e+01]
[  1.49511103e-02   5.00503717e+02   1.06335855e+01]
[  1.49693224e-02   5.00009393e+02   1.01017707e+01]
[  1.49683959e-02   4.99686864e+02   1.00517329e+01]
[  1.49511103e-02   5.00503717e+02   1.06335855e+01]
[  1.49693224e-02   5.00009393e+02   1.01017707e+01]
[  1.49637504e-02   5.00089477e+02   1.05335317e+01]
[  1.49511103e-02   5.00503717e+02   1.06335855e+01]
[  1.49693224e-02   5.00009393e+02   1.01017707e+01]
[  1.49637504e-02   5.00089477e+02   1.05335317e+01]
[  1.49511103e-02   5.00503717e+02   1.06335855e+01]
[  1.49693224e-02   5.00009393e+02   1.0101770

[  1.49938400e-02   4.99906136e+02   1.07330647e+01]
[  1.49660075e-02   5.00653054e+02   1.02292720e+01]
[  1.49445219e-02   5.00909375e+02   1.02140565e+01]
[  1.49988792e-02   5.00091341e+02   1.04469403e+01]
[  1.49780077e-02   5.00468182e+02   1.05862303e+01]
[  1.49445219e-02   5.00909375e+02   1.02140565e+01]
[  1.49988792e-02   5.00091341e+02   1.04469403e+01]
[  1.49780077e-02   5.00468182e+02   1.05862303e+01]
[  1.49517883e-02   5.00750325e+02   1.02855572e+01]
[  1.50040301e-02   5.00640198e+02   1.04591927e+01]
[  1.49780077e-02   5.00468182e+02   1.05862303e+01]
[  1.49517883e-02   5.00750325e+02   1.02855572e+01]
[  1.49942880e-02   4.99137750e+02   1.02841838e+01]
[  1.49435583e-02   5.00762887e+02   1.03947448e+01]
[  1.49601631e-02   5.00145265e+02   1.01032601e+01]
[  1.49942880e-02   4.99137750e+02   1.02841838e+01]
[  1.49435583e-02   5.00762887e+02   1.03947448e+01]
[  1.49601631e-02   5.00145265e+02   1.01032601e+01]
[  1.49739994e-02   4.99161614e+02   1.0144571

[  1.49897013e-02   4.99541354e+02   1.02111031e+01]
[  1.49606238e-02   5.00249121e+02   1.02619276e+01]
[  1.49550999e-02   4.99890619e+02   1.00706659e+01]
[  1.49897013e-02   4.99541354e+02   1.02111031e+01]
[  1.49606238e-02   5.00249121e+02   1.02619276e+01]
[  1.49550999e-02   4.99890619e+02   1.00706659e+01]
[  1.49897013e-02   4.99541354e+02   1.02111031e+01]
[  1.49606238e-02   5.00249121e+02   1.02619276e+01]
[  1.49550999e-02   4.99890619e+02   1.00706659e+01]
[  1.49897013e-02   4.99541354e+02   1.02111031e+01]
[  1.49444884e-02   5.00343703e+02   1.03599644e+01]
[  1.49550999e-02   4.99890619e+02   1.00706659e+01]
[  1.49897013e-02   4.99541354e+02   1.02111031e+01]
[  1.49614847e-02   5.00394977e+02   1.06359001e+01]
[  1.49690588e-02   4.99564656e+02   1.03851939e+01]
[  1.49897013e-02   4.99541354e+02   1.02111031e+01]
[  1.49614847e-02   5.00394977e+02   1.06359001e+01]
[  1.49690588e-02   4.99564656e+02   1.03851939e+01]
[  1.49897013e-02   4.99541354e+02   1.0211103

[  1.49716901e-02   4.99770383e+02   1.04600108e+01]
[  1.49911497e-02   5.00400467e+02   1.04411439e+01]
[  1.49905662e-02   5.00531157e+02   1.05653732e+01]
[  1.49716901e-02   4.99770383e+02   1.04600108e+01]
[  1.49612157e-02   5.00688135e+02   1.01164434e+01]
[  1.49905662e-02   5.00531157e+02   1.05653732e+01]
[  1.49716901e-02   4.99770383e+02   1.04600108e+01]
[  1.49612157e-02   5.00688135e+02   1.01164434e+01]
[  1.49905662e-02   5.00531157e+02   1.05653732e+01]
[  1.49919790e-02   4.99156000e+02   1.00571995e+01]
[  1.49612157e-02   5.00688135e+02   1.01164434e+01]
[  1.49905662e-02   5.00531157e+02   1.05653732e+01]
[  1.49919790e-02   4.99156000e+02   1.00571995e+01]
[  1.49612157e-02   5.00688135e+02   1.01164434e+01]
[  1.49905662e-02   5.00531157e+02   1.05653732e+01]
[  1.49919790e-02   4.99156000e+02   1.00571995e+01]
[  1.49612157e-02   5.00688135e+02   1.01164434e+01]
[  1.49905662e-02   5.00531157e+02   1.05653732e+01]
[  1.49919790e-02   4.99156000e+02   1.0057199

[  1.49529290e-02   5.00864207e+02   1.04008910e+01]
[  1.49565728e-02   5.01528640e+02   1.02715116e+01]
[  1.49840848e-02   4.99374590e+02   1.01779440e+01]
[  1.49529290e-02   5.00864207e+02   1.04008910e+01]
[  1.49565728e-02   5.01528640e+02   1.02715116e+01]
[  1.49840848e-02   4.99374590e+02   1.01779440e+01]
[  1.49529290e-02   5.00864207e+02   1.04008910e+01]
[  1.49565728e-02   5.01528640e+02   1.02715116e+01]
[  1.49840848e-02   4.99374590e+02   1.01779440e+01]
[  1.49529290e-02   5.00864207e+02   1.04008910e+01]
[  1.49753815e-02   5.00980556e+02   1.00211627e+01]
[  1.49840848e-02   4.99374590e+02   1.01779440e+01]
[  1.49529290e-02   5.00864207e+02   1.04008910e+01]
[  1.49753815e-02   5.00980556e+02   1.00211627e+01]
[  1.49840848e-02   4.99374590e+02   1.01779440e+01]
[  1.49529290e-02   5.00864207e+02   1.04008910e+01]
[  1.49917620e-02   5.00267740e+02   9.95319987e+00]
[  1.49840848e-02   4.99374590e+02   1.01779440e+01]
[  1.49896940e-02   5.00039707e+02   1.0635298

[  1.50012968e-02   4.99682295e+02   1.06335534e+01]
[  1.49723154e-02   5.01111453e+02   1.07004175e+01]
[  1.49790356e-02   5.00256024e+02   1.02788277e+01]

KeyboardInterrupt: 

In [ ]:
chains